### PR TITLE
Implement collaboration service 

### PR DESCRIPTION
**Pull request by gmengqi**
- when a match is found, the continue button will not automatically direct to the collaboration room, it will take 5s to navigate to the collaboration room. 
- the question presented in the collaboration room is hardcoded in as of now. 
- a rough frontend for the collaboration room is implemented, can be further improved

### CODE REVIEW

**Comment by chiewyx** [comment]
- continue button will now direct users to collab room
- when user clicks on leave collab button, it notifies the other user and redirects them back to matching page after 5s

**Comment by JunHao247** [comment]
> * when user clicks on leave collab button, it notifies the other user and redirects them back to matching page after 5s

Do we need to redirect the other user? or just leave them inside the room

**Comment by chiewyx** [comment]
> > * when user clicks on leave collab button, it notifies the other user and redirects them back to matching page after 5s
> 
> Do we need to redirect the other user? or just leave them inside the room

hmmm, or we can just notify the user and leave them inside, i think both are fine



> If the user click on other tabs like "Home", when they click back "Matching", they are now at the matching service page.
> 
> Are they considered as "left the room" only after clicking the "Leave Collaboration" button?

i think for now the only way to leave the room properly is through the "leave collab" button

**Comment by chiewyx** [comment]
added retrieval of question instead of hardcoding

**Review by JunHao247 — APPROVED** [review]
LGTM

**Pull request merged**
